version: '3.3'

services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=gestion_usuario
      - POSTGRES_USER=yuver
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    

